version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /templates/fullstack-mono
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /templates/fullstack-mono
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /templates/fullstack-mono
    schedule:
      interval: weekly
